/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;

import java.sql.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author LENOVO
 */
public final class FormList extends javax.swing.JFrame {

    public Statement st;
    public ResultSet rs;
    public DefaultTableModel tabModel;
    Connection cn = koneksi.Koneksi.Koneksi();
    int offset;

    /**
     * Creates new form FormList
     */
    public FormList() {
        initComponents();
        header_table();
        tampil_data();
    }

    FormEdit fe = new FormEdit();

    public int getRowNumber() {
        int numberRow = 0;

        try {
            st = cn.createStatement();
            rs = st.executeQuery("SELECT COUNT(*) FROM data_pasien");
            while (rs.next()) {
                numberRow = rs.getInt("COUNT(*)");
            }
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
        return numberRow;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_header_daftar_pasien = new javax.swing.JPanel();
        txt_daftar_pasien = new javax.swing.JLabel();
        btn_tambah = new javax.swing.JButton();
        btn_keluar = new javax.swing.JButton();
        panel_table_pasien = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_pasien = new javax.swing.JTable();
        panel_pagination = new javax.swing.JPanel();
        btn_prev = new javax.swing.JButton();
        btn_next = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(247, 231, 220));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_header_daftar_pasien.setBackground(new java.awt.Color(247, 231, 220));

        txt_daftar_pasien.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_daftar_pasien.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_daftar_pasien.setText("Daftar Pasien");
        txt_daftar_pasien.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        btn_tambah.setBackground(new java.awt.Color(117, 134, 148));
        btn_tambah.setForeground(new java.awt.Color(255, 255, 255));
        btn_tambah.setText("Tambah");
        btn_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambahActionPerformed(evt);
            }
        });

        btn_keluar.setBackground(new java.awt.Color(117, 134, 148));
        btn_keluar.setForeground(new java.awt.Color(255, 255, 255));
        btn_keluar.setText("Keluar");
        btn_keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_keluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_header_daftar_pasienLayout = new javax.swing.GroupLayout(panel_header_daftar_pasien);
        panel_header_daftar_pasien.setLayout(panel_header_daftar_pasienLayout);
        panel_header_daftar_pasienLayout.setHorizontalGroup(
            panel_header_daftar_pasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_header_daftar_pasienLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(btn_tambah)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                .addComponent(txt_daftar_pasien)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                .addComponent(btn_keluar)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        panel_header_daftar_pasienLayout.setVerticalGroup(
            panel_header_daftar_pasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_header_daftar_pasienLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(panel_header_daftar_pasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_tambah)
                    .addComponent(txt_daftar_pasien)
                    .addComponent(btn_keluar))
                .addGap(2, 2, 2))
        );

        getContentPane().add(panel_header_daftar_pasien, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 50));

        panel_table_pasien.setBackground(new java.awt.Color(247, 231, 220));

        table_pasien.setAutoCreateRowSorter(true);
        table_pasien.setBackground(new java.awt.Color(255, 248, 243));
        table_pasien.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        table_pasien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "No", "Nama", "NIK", "Tanggal Lahir", "Alamat"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_pasien.setAutoscrolls(false);
        table_pasien.setGridColor(new java.awt.Color(255, 248, 243));
        table_pasien.setRowHeight(30);
        table_pasien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_pasienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_pasien);
        if (table_pasien.getColumnModel().getColumnCount() > 0) {
            table_pasien.getColumnModel().getColumn(0).setPreferredWidth(10);
            table_pasien.getColumnModel().getColumn(2).setHeaderValue("NIK");
            table_pasien.getColumnModel().getColumn(3).setHeaderValue("Tanggal Lahir");
            table_pasien.getColumnModel().getColumn(4).setHeaderValue("Alamat");
        }

        javax.swing.GroupLayout panel_table_pasienLayout = new javax.swing.GroupLayout(panel_table_pasien);
        panel_table_pasien.setLayout(panel_table_pasienLayout);
        panel_table_pasienLayout.setHorizontalGroup(
            panel_table_pasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_table_pasienLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        panel_table_pasienLayout.setVerticalGroup(
            panel_table_pasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_table_pasienLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(panel_table_pasien, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 570, 100));

        panel_pagination.setBackground(new java.awt.Color(247, 231, 220));

        btn_prev.setBackground(new java.awt.Color(117, 134, 148));
        btn_prev.setForeground(new java.awt.Color(255, 255, 255));
        btn_prev.setText("<");
        btn_prev.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btn_prevMouseMoved(evt);
            }
        });
        btn_prev.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_prevMousePressed(evt);
            }
        });
        btn_prev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_prevActionPerformed(evt);
            }
        });

        btn_next.setBackground(new java.awt.Color(117, 134, 148));
        btn_next.setForeground(new java.awt.Color(255, 255, 255));
        btn_next.setText(">");
        btn_next.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btn_nextMouseMoved(evt);
            }
        });
        btn_next.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_nextMousePressed(evt);
            }
        });
        btn_next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_paginationLayout = new javax.swing.GroupLayout(panel_pagination);
        panel_pagination.setLayout(panel_paginationLayout);
        panel_paginationLayout.setHorizontalGroup(
            panel_paginationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_paginationLayout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addComponent(btn_prev)
                .addGap(53, 53, 53)
                .addComponent(btn_next)
                .addContainerGap(78, Short.MAX_VALUE))
        );
        panel_paginationLayout.setVerticalGroup(
            panel_paginationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_paginationLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_paginationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_prev)
                    .addComponent(btn_next))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        getContentPane().add(panel_pagination, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 240, 40));

        jPanel1.setBackground(new java.awt.Color(247, 231, 220));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 570, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambahActionPerformed
        FormInput fi = new FormInput();
        fi.show();
        dispose();
    }//GEN-LAST:event_btn_tambahActionPerformed

    private void table_pasienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_pasienMouseClicked
        try {
            int index = table_pasien.getSelectedRow();
            TableModel model = table_pasien.getModel();

            String nik = model.getValueAt(index, 2).toString();

            st = cn.createStatement();
            tabModel.getDataVector().removeAllElements();
            tabModel.fireTableDataChanged();
            rs = st.executeQuery("SELECT * FROM data_pasien WHERE nik=" + nik + "");

            if (rs.next()) {
                fe.show();
                dispose();

                fe.txt_id_pasien.setText(rs.getString("id_pasien"));
                fe.input_nama.setText(rs.getString("nama"));
                fe.input_nik.setText(rs.getString("nik"));
                fe.input_tgl_lahir.setDate(rs.getDate("tgl_lahir"));
                fe.input_alamat.setText(rs.getString("alamat"));
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_table_pasienMouseClicked

    private void btn_prevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_prevActionPerformed
        try {
            offset--;
            st = cn.createStatement();
            tabModel.getDataVector().removeAllElements();
            tabModel.fireTableDataChanged();
            rs = st.executeQuery("SELECT id_pasien, nama, nik, DATE_FORMAT(tgl_lahir, '%Y-%b-%d') AS tgl_lahir, alamat FROM data_pasien LIMIT " + offset + ", 1");

            while (rs.next()) {
                Object[] data = {
                    rs.getString("id_pasien"),
                    rs.getString("nama"),
                    rs.getString("nik"),
                    rs.getString("tgl_lahir"),
                    rs.getString("alamat")
                };

                tabModel.addRow(data);
            }

        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btn_prevActionPerformed

    private void btn_nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nextActionPerformed
        try {
            offset++;
            st = cn.createStatement();
            tabModel.getDataVector().removeAllElements();
            tabModel.fireTableDataChanged();
            rs = st.executeQuery("SELECT id_pasien, nama, nik, DATE_FORMAT(tgl_lahir, '%Y-%b-%d') AS tgl_lahir, alamat FROM data_pasien LIMIT " + offset + ", 1");

            while (rs.next()) {
                Object[] data = {
                    rs.getString("id_pasien"),
                    rs.getString("nama"),
                    rs.getString("nik"),
                    rs.getString("tgl_lahir"),
                    rs.getString("alamat")
                };

                tabModel.addRow(data);
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btn_nextActionPerformed

    private void btn_prevMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_prevMousePressed
        if (offset <= 0) {
            btn_prev.setEnabled(false);
        } else {
            btn_prev.setEnabled(true);
        }
    }//GEN-LAST:event_btn_prevMousePressed

    private void btn_prevMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_prevMouseMoved
        if (offset <= 0) {
            btn_prev.setEnabled(false);
        } else {
            btn_prev.setEnabled(true);
        }
    }//GEN-LAST:event_btn_prevMouseMoved

    private void btn_nextMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_nextMousePressed
        if ((offset + 1) >= getRowNumber()) {
            btn_next.setEnabled(false);
        } else {
            btn_next.setEnabled(true);
        }
    }//GEN-LAST:event_btn_nextMousePressed

    private void btn_nextMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_nextMouseMoved
        if ((offset + 1) >= getRowNumber()) {
            btn_next.setEnabled(false);
        } else {
            btn_next.setEnabled(true);
        }
    }//GEN-LAST:event_btn_nextMouseMoved

    private void btn_keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_keluarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btn_keluarActionPerformed

    public void header_table() {
        Object[] header_table = {
            "No", "Nama", "NIK", "Tanggal Lahir", "Alamat"
        };
        tabModel = new DefaultTableModel(null, header_table);
        table_pasien.setModel(tabModel);
    }

    public void tampil_data() {
        try {
            st = cn.createStatement();
            tabModel.getDataVector().removeAllElements();
            tabModel.fireTableDataChanged();
            rs = st.executeQuery("SELECT id_pasien, nama, nik, DATE_FORMAT(tgl_lahir, '%Y-%b-%d') AS tgl_lahir, alamat FROM data_pasien LIMIT 1");

            while (rs.next()) {
                Object[] data = {
                    rs.getString("id_pasien"),
                    rs.getString("nama"),
                    rs.getString("nik"),
                    rs.getString("tgl_lahir"),
                    rs.getString("alamat")
                };

                tabModel.addRow(data);
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FormList().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_keluar;
    private javax.swing.JButton btn_next;
    private javax.swing.JButton btn_prev;
    private javax.swing.JButton btn_tambah;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panel_header_daftar_pasien;
    private javax.swing.JPanel panel_pagination;
    private javax.swing.JPanel panel_table_pasien;
    private javax.swing.JTable table_pasien;
    private javax.swing.JLabel txt_daftar_pasien;
    // End of variables declaration//GEN-END:variables
}
