/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;

import java.sql.*;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LENOVO
 */
public class FormEdit extends javax.swing.JFrame {

    public Statement st;
    public ResultSet rs;
    public DefaultTableModel tabModel;
    Connection cn = koneksi.Koneksi.Koneksi();
    

    /**
     * Creates new form FormEdit
     */
    public FormEdit() {
        initComponents();
        txt_id_pasien.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_form_input = new javax.swing.JPanel();
        txt_header_form_edit = new javax.swing.JLabel();
        txt_alamat = new javax.swing.JLabel();
        input_nik = new javax.swing.JTextField();
        input_nama = new javax.swing.JTextField();
        txt_tgl_lahir = new javax.swing.JLabel();
        txt_nik = new javax.swing.JLabel();
        txt_nama = new javax.swing.JLabel();
        btn_kembali = new javax.swing.JButton();
        txt_id_pasien = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        input_alamat = new javax.swing.JTextArea();
        btn_keluar = new javax.swing.JButton();
        input_tgl_lahir = new com.toedter.calendar.JDateChooser();
        panel_button_form_input = new javax.swing.JPanel();
        btn_hapus = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setMinimumSize(new java.awt.Dimension(640, 420));
        setPreferredSize(new java.awt.Dimension(640, 420));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_form_input.setBackground(new java.awt.Color(247, 231, 220));

        txt_header_form_edit.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_header_form_edit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_header_form_edit.setText("Edit Data Pasien");
        txt_header_form_edit.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        txt_alamat.setText("Alamat");

        input_nik.setBackground(new java.awt.Color(255, 248, 243));
        input_nik.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                input_nikKeyTyped(evt);
            }
        });

        input_nama.setEditable(false);
        input_nama.setBackground(new java.awt.Color(255, 248, 243));

        txt_tgl_lahir.setText("Tanggal Lahir");

        txt_nik.setText("NIK");

        txt_nama.setText("Nama Pasien");

        btn_kembali.setBackground(new java.awt.Color(117, 134, 148));
        btn_kembali.setForeground(new java.awt.Color(255, 255, 255));
        btn_kembali.setText("Kembali");
        btn_kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kembaliActionPerformed(evt);
            }
        });

        txt_id_pasien.setBackground(new java.awt.Color(255, 255, 255));
        txt_id_pasien.setText("id_pasien");
        txt_id_pasien.setToolTipText("");
        txt_id_pasien.setAlignmentX(0.5F);

        input_alamat.setBackground(new java.awt.Color(255, 248, 243));
        input_alamat.setColumns(20);
        input_alamat.setRows(5);
        jScrollPane1.setViewportView(input_alamat);

        btn_keluar.setBackground(new java.awt.Color(117, 134, 148));
        btn_keluar.setForeground(new java.awt.Color(255, 255, 255));
        btn_keluar.setText("Keluar");
        btn_keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_keluarActionPerformed(evt);
            }
        });

        input_tgl_lahir.setBackground(new java.awt.Color(255, 248, 243));

        javax.swing.GroupLayout panel_form_inputLayout = new javax.swing.GroupLayout(panel_form_input);
        panel_form_input.setLayout(panel_form_inputLayout);
        panel_form_inputLayout.setHorizontalGroup(
            panel_form_inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_form_inputLayout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addGroup(panel_form_inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panel_form_inputLayout.createSequentialGroup()
                        .addGroup(panel_form_inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_nik)
                            .addComponent(txt_tgl_lahir)
                            .addComponent(txt_nama)
                            .addComponent(txt_alamat))
                        .addGap(32, 32, 32)
                        .addGroup(panel_form_inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(input_nik)
                            .addComponent(input_nama)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE)
                            .addComponent(input_tgl_lahir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(panel_form_inputLayout.createSequentialGroup()
                        .addComponent(btn_kembali)
                        .addGap(124, 124, 124)
                        .addComponent(txt_header_form_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_id_pasien)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                        .addComponent(btn_keluar)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        panel_form_inputLayout.setVerticalGroup(
            panel_form_inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_form_inputLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_form_inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_header_form_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_kembali)
                    .addComponent(txt_id_pasien)
                    .addComponent(btn_keluar))
                .addGap(34, 34, 34)
                .addGroup(panel_form_inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel_form_inputLayout.createSequentialGroup()
                        .addGroup(panel_form_inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(input_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_nama))
                        .addGap(27, 27, 27)
                        .addGroup(panel_form_inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_nik)
                            .addComponent(input_nik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addComponent(input_tgl_lahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txt_tgl_lahir))
                .addGroup(panel_form_inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_form_inputLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(txt_alamat))
                    .addGroup(panel_form_inputLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        getContentPane().add(panel_form_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 340));

        panel_button_form_input.setBackground(new java.awt.Color(247, 231, 220));

        btn_hapus.setBackground(new java.awt.Color(117, 134, 148));
        btn_hapus.setForeground(new java.awt.Color(255, 255, 255));
        btn_hapus.setText("Hapus Data");
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });

        btn_update.setBackground(new java.awt.Color(117, 134, 148));
        btn_update.setForeground(new java.awt.Color(255, 255, 255));
        btn_update.setText("Update Data");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_button_form_inputLayout = new javax.swing.GroupLayout(panel_button_form_input);
        panel_button_form_input.setLayout(panel_button_form_inputLayout);
        panel_button_form_inputLayout.setHorizontalGroup(
            panel_button_form_inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_button_form_inputLayout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addComponent(btn_hapus)
                .addGap(88, 88, 88)
                .addComponent(btn_update)
                .addContainerGap(196, Short.MAX_VALUE))
        );
        panel_button_form_inputLayout.setVerticalGroup(
            panel_button_form_inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_button_form_inputLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_button_form_inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_hapus)
                    .addComponent(btn_update))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        getContentPane().add(panel_button_form_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 640, 60));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        try {
            int jawab;

            if ((jawab = JOptionPane.showConfirmDialog(null, "Ingin Menghapus Data Ini?", "Yes", JOptionPane.YES_NO_OPTION)) == 0) {
                st = cn.createStatement();
                st.executeUpdate("DELETE FROM data_pasien WHERE id_pasien='" + txt_id_pasien.getText() + "'");
            }

            JOptionPane.showMessageDialog(null, "Hapus Data Pasien Berhasil!");

            FormList fl = new FormList();
            fl.show();
            dispose();
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        try {
            st = cn.createStatement();

            if (input_nama.getText() == "") {
                JOptionPane.showMessageDialog(null, "Nama pasien tidak boleh kosong!");
            } else if (input_nik.getText() == "") {
                JOptionPane.showMessageDialog(null, "NIK tidak boleh kosong!");
            } else if (input_tgl_lahir.getDate() == null) {
                JOptionPane.showMessageDialog(null, "Nama pasien tidak boleh kosong!");
            } else if (input_alamat.getText() == "") {
                JOptionPane.showMessageDialog(null, "Alamat tidak boleh kosong!");
            } else {
                rs = st.executeQuery("SELECT * FROM data_pasien WHERE nik = " + input_nik.getText() + " AND NOT id_pasien = " + txt_id_pasien.getText() + "");
                if (rs.next()) {
                    JOptionPane.showMessageDialog(null, "NIK : '" + input_nik.getText() + "' sudah terpakai!");
                    input_nik.setText("");
                } else {
                    st.executeUpdate("UPDATE data_pasien SET nama = '" + input_nama.getText() + "', nik = '" + input_nik.getText() + "', alamat = '" + input_alamat.getText() + "', tgl_lahir = '" + new SimpleDateFormat("yyyy-MM-dd").format(input_tgl_lahir.getDate()) + "' WHERE id_pasien = '" + txt_id_pasien.getText() + "'");

                    JOptionPane.showMessageDialog(null, "Update Data Pasien Berhasil");

                    FormList fl = new FormList();
                    fl.show();
                    dispose();
                }
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btn_updateActionPerformed

    private void btn_kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kembaliActionPerformed
        FormList fl = new FormList();
        fl.show();
        dispose();
    }//GEN-LAST:event_btn_kembaliActionPerformed

    private void input_nikKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_input_nikKeyTyped
        if (!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_input_nikKeyTyped

    private void btn_keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_keluarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btn_keluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormEdit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_keluar;
    private javax.swing.JButton btn_kembali;
    private javax.swing.JButton btn_update;
    public javax.swing.JTextArea input_alamat;
    public javax.swing.JTextField input_nama;
    public javax.swing.JTextField input_nik;
    public com.toedter.calendar.JDateChooser input_tgl_lahir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panel_button_form_input;
    private javax.swing.JPanel panel_form_input;
    private javax.swing.JLabel txt_alamat;
    private javax.swing.JLabel txt_header_form_edit;
    public javax.swing.JLabel txt_id_pasien;
    private javax.swing.JLabel txt_nama;
    private javax.swing.JLabel txt_nik;
    private javax.swing.JLabel txt_tgl_lahir;
    // End of variables declaration//GEN-END:variables
}
